#!/usr/bin/env python3
#
# nlv
#
# Copyright (c) 2017 endaaman
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.

import sys, nlv

if __name__ == '__main__':
    sys.exit(nlv.main())
